apiVersion: v1
kind: Service
metadata:
  name: samsara-postgres
  labels:
    app: samsara
spec:
  ports:
    - port: 5432
  selector:
    app: samsara
    tier: postgres
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvol-claim
  labels:
    app: samsara
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: samsara-postgres
  labels:
    app: samsara
spec:
  selector:
    matchLabels:
      app: samsara
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: samsara
        tier: postgres
    spec:
      containers:
      - image: 370535134506.dkr.ecr.us-west-2.amazonaws.com/db:latest
        name: postgres
        env:
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: auradb
        - name: DB_USER
          value: aura
        - name: DB_PASS
          value: mysecretpassword
#        - name: DB_PASS
#          valueFrom:
#            secretKeyRef:
#              name: dbuser-pass
#              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-volume
          mountPath: /var/lib/postgresql
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-pvol-claim