apiVersion: v1
kind: Service
metadata:
  name: samsara
  labels:
    app: samsara
spec:
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: samsara
    tier: backend
  type: LoadBalancer

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: samsara
  labels:
    app: samsara
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samsara
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: samsara
        tier: backend
    spec:
      containers:
      - image: registry.lerkasan.de:5000/samsara:latest
        imagePullPolicy: "Always"
        name: samsara
        env:
        - name: DB_HOST
          value: samsara-postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: auradb
        - name: DB_USER
          value: aura
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: dbuser-pass
              key: password
        ports:
        - containerPort: 9000
          name: samsara